name: neuron_merging 
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - ca-certificates
  - certifi
  - cudatoolkit
  - freetype
  - intel-openmp
  - joblib
  - jpeg
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libtiff
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pillow
  - pip
  - python
  - pytorch
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - tk
  - torchvision
  - wheel
  - xz
  - zlib
  - zstd

